---

- name: Download kernel source
  get_url:
    url: "{{ kernel_source_url }}"
    dest: /usr/src/
    timeout: 20
  tags: kernel-build

- name: Expand kernel source archive
  unarchive:
    src: /usr/src/{{ kernel_source_archive }}
    dest: /usr/src/
    copy: no
  tags: kernel-build

#- name: Download OVH kernel config
#  get_url:
#    url: "{{ ovh_config_url }}"
#    dest: /usr/src/.config
#    timeout: 20
#  tags: kernel-build

- name: Download OVH kernel config
  shell: wget {{ ovh_config_url }} -O {{ kernel_source_directory }}/.config
  args:
    creates: /usr/src/{{ kernel_source_directory }}/.config
    chdir: /usr/src/
  tags: kernel-build

- name: Replace perf config file
  copy:
    src: Makefile.perf
    dest: /usr/src/{{ kernel_source_directory }}/tools/perf/Makefile.perf
  tags: kernel-build, now

- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - gcc
    - make
    - git
    - libssl-dev
    - libncurses5-dev
    - flex
    - bison
    - python-dev
    - libelf-dev
    - libdw-dev
    - libnewt-dev
    - libunwind-dev
    - libaudit-dev
    - libslang2-dev
    - binutils-dev
    - libnuma-dev
    - libperl-dev
    - libpython-dev
    - libgtk2.0-dev
    - libunwind-dev
    - libunwind-setjmp0-dev
    - libiberty-dev
  tags: kernel-build
